dataset_path: c:\Users\ksilva\Documents\Wave_Estimator\Smooth\ATL/dataset_smh_01.csv
test_size: 0.2
random_state: 40
target: ['Hs', 'Tp', 'dir']
cv_splits: 5
model_params:
  #n_estimators: 30
  random_state: 40
  #criterion: 'squared_error'
  #max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 2

param_grid:
  n_estimators: [10, 30]
  max_depth: [10]
  min_samples_split: [6]
  min_samples_leaf: [2]
  criterion: ['squared_error', 'absolute_error']
metrics:
  - mae
  - mse
  - rmse
  - acc
