dataset_path: c:\Users\ksilva\Documents\finep dados\IA_ML\ML\Smooth\ATL/dataset_smh_01.csv
test_size: 0.2
random_state: 40
target: ['Hs', 'Tp', 'dir']
model_params:
  n_estimators: 30
  random_state: 40
  criterion: 'squared_error'
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 2

param_grid:
  n_estimators: [10, 20, 30, 40, 50, 100]
  max_depth: [2, 3, 5, 10, 30]
  min_samples_split: [2, 4, 6]
  min_samples_leaf: [1, 2, 3]
metrics:
  - mae
  - mse
  - rmse
  - acc
