#dataset_path: c:\Users\ksilva\Documents\Wave_Estimator\Smooth\ATL/dataset_smh_01.csv
dataset_path: c:\Users\ksilva\Documents\Wave_Estimator\dados\processados/dataset_smh_02.csv

test_size: 0.8
random_state: 40
#target: ['Hs', 'Tp', 'dir']
target: ['Hs']
cv_splits: 5
model_params:
  #n_estimators: 30
  random_state: 40
  #criterion: 'squared_error'
  #max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 2

param_grid:
  n_estimators: [10, 30, 50]
  max_depth: [2 ,10, None]
  min_samples_split: [2, 6]
  min_samples_leaf: [1, 2]
  criterion: ['squared_error', 'absolute_error']
metrics:
  - mae
  - mse
  - rmse
  - acc
