dataset_path: c:\Users\ksilva\Documents\Wave_Estimator\dados\processados/dataset_02_atl_new_hd.csv


test_size: 0.8
random_state: 40
#target: ['Hs', 'Tp', 'dir']
#target: ['dir']
target: ['Hs']
#cv_splits: 5
#model_params:

metrics:
  - mae
  - mse
  - rmse
  - acc
